TheTopProject/Models/Tasks.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace TheTopProject.Models
{
    public partial class Tasks
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string TaskContent { get; set; }
        public DateTime InsertTime { get; set; }
        public DateTime FinishTime { get; set; }
        public bool? Done { get; set; }
        public int EmployeeId { get; set; }

        public virtual Employee Employee { get; set; }
    }
}

TheTopProject/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheTopProject.Models;

namespace TheTopProject.Controllers
{
    public class TasksController : Controller
    {
        private readonly TheTopDatabaseContext _context;
        const string AName = "Aname";
        const string EId = "EId";
        const string EAName = "EAname";

        const string AEName = "AEname";
        public TasksController(TheTopDatabaseContext context)
        {
            _context = context;
        }

        // GET: Tasks
        public async Task<IActionResult> Index()
        {
            TempData[AName] = HttpContext.Session.GetString(AName);
            TempData[EId] = HttpContext.Session.GetInt32(EId);
            TempData[EAName] = HttpContext.Session.GetString(EAName);

            TempData[AEName] = HttpContext.Session.GetString(AEName);
            var theTopDatabaseContext = _context.Tasks.Include(t => t.Employee).OrderByDescending(x => x.InsertTime);
            
            if(TempData[EId] != null)
                 theTopDatabaseContext = _context.Tasks.Include(t => t.Employee).Where(x=> x.Employee.Id ==Convert.ToInt32(TempData[EId])).OrderByDescending(x => x.InsertTime);
         
            
            return View(await theTopDatabaseContext.ToListAsync());
        }
        public async Task<IActionResult> Finish()
        {
            TempData[AName] = HttpContext.Session.GetString(AName);
            
            return View("Index", await _context.Tasks.OrderByDescending(x => x.InsertTime).Where(x=>x.Done == true).ToListAsync());
        }
        public async Task<IActionResult> UnFinish()
        {
            TempData[AName] = HttpContext.Session.GetString(AName);
            
            return View("Index", await _context.Tasks.OrderByDescending(x => x.InsertTime).Where(x => x.Done == false).ToListAsync());
        }
        public async Task<IActionResult> DeleteConfirmed1(int id)
        {
            TempData[AName] = HttpContext.Session.GetString(AName);
           
            var task = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(task);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // GET: Tasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks
                .Include(t => t.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tasks == null)
            {
                return NotFound();
            }

            return View(tasks);
        }

        // GET: Tasks/Create
        public IActionResult Create()
        {
            TempData[AName] = HttpContext.Session.GetString(AName);
            
            ViewData["EmployeeId"] = new SelectList(_context.Employee, "Id", "Email" );
            return View();
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Subject,TaskContent,InsertTime,FinishTime,Done,EmployeeId")] Tasks tasks)
        {
            if (ModelState.IsValid)
            {
                tasks.Done = false;
                tasks.InsertTime = DateTime.Now;
                _context.Add(tasks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employee, "Id", "DepartmentName", tasks.EmployeeId);
            return View(tasks);
        }

        // GET: Tasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            TempData[AName] = HttpContext.Session.GetString(AName);
            
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks.FindAsync(id);
            if (tasks == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employee, "Id", "DepartmentName", tasks.EmployeeId);
            return View(tasks);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Subject,TaskContent,InsertTime,FinishTime,Done,EmployeeId")] Tasks tasks)
        {
            if (id != tasks.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tasks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TasksExists(tasks.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employee, "Id", "DepartmentName", tasks.EmployeeId);
            return View(tasks);
        }

        // GET: Tasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            TempData[AName] = HttpContext.Session.GetString(AName);
          
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks
                .Include(t => t.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tasks == null)
            {
                return NotFound();
            }

            return View(tasks);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tasks = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(tasks);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Finished(int id)
        {
            TempData[AName] = HttpContext.Session.GetString(AName);
            
            Tasks task = _context.Tasks.Find(id);
            if (id != task.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                task.Done = true;
                _context.Update(task);
                await _context.SaveChangesAsync();

            }
            return RedirectToAction(nameof(Index));
            //return View(contact);
        }

        public async Task<IActionResult> UnFinished(int id)
        {
            TempData[AName] = HttpContext.Session.GetString(AName);
           
            Tasks task = _context.Tasks.Find(id);
            if (id != task.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                task.Done = false;
                _context.Update(task);
                await _context.SaveChangesAsync();

            }
            return RedirectToAction(nameof(Index));
            //return View(contact);
        }
        private bool TasksExists(int id)
        {
            return _context.Tasks.Any(e => e.Id == id);
        }
    }
}

TheTopProject/Views/Tasks/Create.cshtml
@model TheTopProject.Models.Tasks

@{
    ViewData["Title"] = "Create";
}
@{
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div style="margin:5% 20% 0% 40% ">
    <h1>Create</h1>

    <h4>Tasks</h4>
    <hr />
    <div class="row">
        <div class="col-md-6" style="margin-left:4%">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Subject" class="control-label"></label>
                    <input asp-for="Subject" class="form-control" />
                    <span asp-validation-for="Subject" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TaskContent" class="control-label"></label>
                    <input asp-for="TaskContent" class="form-control" />
                    <span asp-validation-for="TaskContent" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FinishTime" class="control-label"></label>
                    <input asp-for="FinishTime" class="form-control" />
                    <span asp-validation-for="FinishTime" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="EmployeeId" class="control-label"></label>
                    <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

 
</div>
@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
@RenderSection("scripts")*@

TheTopProject/Views/Tasks/Delete.cshtml
@model TheTopProject.Models.Tasks

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tasks</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InsertTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InsertTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Done)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Done)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.DepartmentName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TheTopProject/Views/Tasks/Details.cshtml
@model TheTopProject.Models.Tasks

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tasks</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InsertTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InsertTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Done)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Done)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.DepartmentName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TheTopProject/Views/Tasks/Edit.cshtml
@model TheTopProject.Models.Tasks

@{
    ViewData["Title"] = "Edit";
}
@{
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<h1>Edit</h1>

<h4>Tasks</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskContent" class="control-label"></label>
                <input asp-for="TaskContent" class="form-control" />
                <span asp-validation-for="TaskContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InsertTime" class="control-label"></label>
                <input asp-for="InsertTime" class="form-control" />
                <span asp-validation-for="InsertTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishTime" class="control-label"></label>
                <input asp-for="FinishTime" class="form-control" />
                <span asp-validation-for="FinishTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Done" class="control-label"></label>
                <input asp-for="Done" class="form-control" />
                <span asp-validation-for="Done" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TheTopProject/Views/Tasks/Index.cshtml
@model IEnumerable<TheTopProject.Models.Tasks>

@{
    ViewData["Title"] = "Index";
}





@{
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<link href="~/Tassets/css/owl.carousel.min.css" rel="stylesheet" />
<link href="~/Tassets/css/style.css" rel="stylesheet" />


<div class="content">

    <div class="container t" style=" margin:0% 20% 0% 21%">
        <h2 class="mb-5" style="text-align:center">Tasks</h2>
        <br /> 
      
       
        <br />
        <div class="form-content form-inline">
            <form asp-action="Index" asp-controller="Tasks" class="inline" style="inset-inline:initial">
                <div class="btn-group">
                    <a asp-action="Index" asp-controller="Tasks" class="btn btn-primary active" aria-current="page">All</a>

                    <a asp-action="Finish" asp-controller="Tasks" class="btn btn-primary ">Finished</a>
                    <a asp-action="UnFinish" asp-controller="Tasks" class="btn btn-primary">not Finished</a>
                </div>
            </form>
            
        </div>
        <div class="table-responsive custom-table-responsive">

            <table class="table custom-table">
                <thead>
                    <tr style="text-align:center">
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Subject)
                        </th>

                        <th scope="col">
                            @Html.DisplayNameFor(model => model.TaskContent)
                        </th>

                        <th scope="col">
                            Added Time
                        </th>

                        <th scope="col">
                            Finished Time
                        </th>


                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Employee)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Done)
                        </th>
                        <th scope="col">
                        </th>
                    </tr>
                </thead>
                <tbody style="text-align:center">
                    @foreach (var item in Model)
                    {
                    <tr scope="row">


                        <td>
                            @Html.DisplayFor(modelItem => item.Subject)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TaskContent)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InsertTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FinishTime)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Employee.Email)
                        </td>
                        <td>
                            @item.Done
                        </td>
                        <td>
                            @if (item.Done == false)
                            {
                                <a asp-action="Finished" asp-route-id="@item.Id">Finished</a>
                            }
                            else
                            {
                                <a asp-action="UnFinished" asp-route-id="@item.Id">UnFinished</a>
                            }
                        </td>
                        <td>
                            
                            <a asp-action="DeleteConfirmed1" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                        <tr class="spacer"><td colspan="100"></td></tr>


                    }

                </tbody>
            </table>
        </div>


    </div>

</div>

<script src="~/Tassets/js/jquery-3.3.1.min.js"></script>
<script src="~/Tassets/js/main.js"></script>
<script src="~/Tassets/js/owl.carousel.min.js"></script>
<script src="~/Tassets/js/popper.min.js"></script>